### ISSUE TITLE
你好，http://acfunfix.sinaapp.com/mama.php 的源码能提供吗？

### ISSUE THREAD

**Issue by zwh8800** [zythum/mama2#103]
你好，http://acfunfix.sinaapp.com/mama.php 的源码能提供吗？

**Comment by A-Circle-Zhang** [comment]
抱歉，这个是不公开，这个是直接从我们商业项目里面提出来的一个接口，里面用到了很多官方的非公开接口和技巧，公开的话会很导致很麻烦的后果。

**Comment by zwh8800** [comment]
大致原理能透露一二吗？我主要想抓取斗鱼tv的直播流。

**Comment by A-Circle-Zhang** [comment]
https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/douyutv.py
可以看看这里。

**Comment by zwh8800** [comment]
@A-Circle-Zhang 十分感谢
