### ISSUE TITLE
seeker_91porn.js可以达到效果吗？

### ISSUE THREAD

**Issue by haloboom** [zythum/mama2#105]
粗略读了下代码，手工抓了下参数，返回的url是加密的貌似？
file=http%3A%2F%2Fd.9p1.space%3A8080%2F%2Fdl%2F%2Fc727f0949c05834b33a4f6eef25f84b1%2F56ac4b9f%2F%2F91porn%2Fmp43%2F145837.mp4
---------------2016.02.02------------------
http://a.9p1.space:8080/mp43/145911.mp4
无意间发现了明文的存储服务器的url？只不过403

**Comment by zythum** [comment]
@SnoozeZ

**Comment by ko0v3e** [comment]
http://fulicdn.qiniudn.com/91p.js
看看这个@haloboom @zythum
