### ISSUE TITLE
我也有尝试改写mama2，微博，百度文库的，百度云的

### ISSUE THREAD

**Issue by funfunhey** [zythum/mama2#106]
现在的成果是，支持微博秒拍，百度文库默认视频，百度云做不到，是能获得百度云的视频连接，然而百度做了反热链的机制，我有尝试修改cookie，好像不咋好使，所以，求朱一大大思路，（ps：发现用safari代理更爽_(:зゝ∠)_）

**Comment by zythum** [comment]
百度云呀。 那我去试试去....

**Comment by zythum** [comment]
百度盘已经搞了下了。你可以去看下代码实现。其实非常简单。掉两个接口完事。从检测网络到大体搜下代码逻辑不到半小时吧。

**Comment by funfunhey** [comment]
造了。。。你用的是下载源，我只研究了web的，找到的接口就有限制，其实我有尝试查看用下载源的网络的，然而百度云管家出面阻止了，让我白白研究n久。。。。。。，论不安装百度全家桶的好处（虽然暂时只有百度云管家）
