### ISSUE TITLE
樂視雲盤解析

### ISSUE THREAD

**Issue by shinrenpan** [zythum/mama2#11]
不熟 node js
但是樂視雲盤是透過底下 url 就可以解析出影片, 例如點選了自己雲盤上的某個影片
http://cloud.letv.com/webdisk/play/video?vid=150326003109000093150311221486

透過以下網址就可以返回一組 JSON
```
http://cloud.letv.com/ledisk/gpc/index?vid=150326003109000093150311221486&cf=ios
```

當然前提是已經 **login** 樂視雲盤

**Comment by zythum** [comment]
https://github.com/zythum/mama2/issues/104
