### ISSUE TITLE
求获取 百度盘 m3u8

### ISSUE THREAD

**Issue by jw007800** [zythum/mama2#111]
上次在 一个叫 “猎人影视”的app 看到 人家居然把百度云盘 的视频直接 m3u8 输出。太神奇了。
http://pan.baidu.com/share/streaming?channel=chunlei&uk=23044168&type=M3U8_AUTO_480&path=/%E8%BA%AB%E6%9D%90%E6%98%AF/%5B%E4%B8%83%E6%B1%89%E5%BD%B1%E8%A7%86%5DYoung.and.Hungry.S03E01.720p.chs_eng.mp4&sign=56d094da02298902d1af24141dd860f94ea84b25&timestamp=1455783853&shareid=1345104365
不知道怎么搞的。
还有迅雷云播。要是能把这两个搞定，就有福利了  哈哈~

**Comment by A-Circle-Zhang** [comment]
做盗版站就得自己花功夫，不会花功夫就花钱，上网求不来的。

**Comment by zythum** [comment]
百度盘今天折腾了下。但是取的是下载源。所以如果是mp4的文件。应该可以看了。方法挺简单的。但是我在公司发现速度慢的不要不要的。不知道是公司网络的问题还是baidu的问题。
