### ISSUE TITLE
优酷只能支持到标清

### ISSUE THREAD

**Issue by cevin** [zythum/mama2#117]
解析不了高清和超清的。

**Comment by A-Circle-Zhang** [comment]
Windows 下不支持。

**Comment by A-Circle-Zhang** [comment]
如果播放器支持分段 MP4，倒是可以将清晰度提高到高清，但那实现起来可能麻烦许多。

**Comment by cevin** [comment]
或许可以调用第三方js解码库？不用自己手动处理。https://github.com/RReverser/mpegts
