### ISSUE TITLE
Bilibili 只能解析到标清

### ISSUE THREAD

**Issue by XIAZY** [zythum/mama2#119]
使用 OS X 10.11 Safari，希望添加解析至高清视频的功能

**Comment by zythum** [comment]
目前我取的bilibili的源就只有这个格式，看看还有别的方法没

**Comment by XIAZY** [comment]
有是有的，但是不会 JS……给 Python 不知行不

**Comment by gdshen95** [comment]
Python是哪个库？

**Comment by XIAZY** [comment]
[fuckbilibili](https://www.fuckbilibili.com/) 上有代码

发自我的 iPad

**Comment by zythum** [comment]
搞定
