### ISSUE TITLE
卧槽，你是v2ex上面那个妹子

### ISSUE THREAD

**Issue by nikogu** [zythum/mama2#14]
竟然还写了个插件。

**Comment by zythum** [comment]
你好。我是正正经经的开发者。不只是会卖萌好不好。不要问没有营养的问题.

**Comment by nikogu** [comment]
issue 不是用来问问题的，是交流的方式，谢谢，你在github上建了项目，我们大家都有权来提issue，干嘛说我的issue是没有营养的问题。话题到此结束，close.

**Comment by zythum** [comment]
＝ ＝。 好有营养。
