### ISSUE TITLE
解析错误情况

### ISSUE THREAD

**Issue by bloodspasm** [zythum/mama2#144]
正常电脑浏览器是可以解析播放的，
我自己用js调用(全部无法播放)解析显示的是移动端的地址但是无法播放?

js部分:void(function(u,s){s=document.body.appendChild(document.createElement('script'));s.src=u+'?ts='+Date.now();s.charset='UTF-8'}('http://zythum.sinaapp.com/mama2/dest/index.js'))

<span style="color:#DF6558">MAMA2 &gt;</span> 解析内容地址完成<a href="http://pl.youku.com/playlist/m3u8?vid=398416034&amp;type=hd2&amp;ctype=12&amp;keyframe=1&amp;ep=dyaSHkGKVs4J4ifWjj8bYni2JnENXP0D%2FhuEh9JhBNQmTeu7&amp;sid=5464870097496125ddb62&amp;token=2534&amp;ev=1&amp;oip=1988394281" target="_blank">超清</a> <a href="http://pl.youku.com/playlist/m3u8?vid=398416034&amp;type=mp4&amp;ctype=12&amp;keyframe=1&amp;ep=dyaSHkGKVs4J4ifWjj8bYni2JnENXP0D%2FhuEh9JhBNQmTeu7&amp;sid=5464870097496125ddb62&amp;token=2534&amp;ev=1&amp;oip=1988394281" target="_blank">高清</a> <a href="http://pl.youku.com/playlist/m3u8?vid=398416034&amp;type=flv&amp;ctype=12&amp;keyframe=1&amp;ep=dyaSHkGKVs4J4ifWjj8bYni2JnENXP0D%2FhuEh9JhBNQmTeu7&amp;sid=5464870097496125ddb62&amp;token=2534&amp;ev=1&amp;oip=1988394281" target="_blank">标清</a>

**Comment by zythum** [comment]
我没支持移动端地址啊...
