### ISSUE TITLE
youku 无法选择清晰度

### ISSUE THREAD

**Issue by cuilili** [zythum/mama2#145]
js下载下来的m3u8文件里面没有数据。 

m3u8内容如下：
#EXTM3U
#EXT-X-TARGETDURATION:-1
#EXT-X-VERSION:3
#EXT-X-ENDLIST

**Comment by bloodspasm** [comment]
对我也是

**Comment by zythum** [comment]
m3u8 本身只是个寻址文件。并没有视频内容的

**Comment by bloodspasm** [comment]
为什么移动端和网页端得到的结果不一样，比较奇怪
