### ISSUE TITLE
B站解析失败

### ISSUE THREAD

**Issue by nukc** [zythum/mama2#147]
这个网址：http://bangumi.bilibili.com/anime/v/41575

**Comment by zythum** [comment]
已合并, 但是你提交的有问题。 我还是改了下...

**Comment by nukc** [comment]
@MarcoQin @zythum 感谢，现在已经能看了。:)

**Comment by nukc** [comment]
刚刚看了内容，发现解析到的都是第1集的视频。

**Comment by MarcoQin** [comment]
@nukc 收到，我再修正一下。

**Comment by MarcoQin** [comment]
@nukc 已修复，等待master merge.
