### ISSUE TITLE
希望支持ZEALER 网站的乐视云

### ISSUE THREAD

**Issue by heixiaoxiazi** [zythum/mama2#16]
ZEALER 王自如的视频都是乐视云的，希望朱一可以考虑一下，（估计很小众也不会支持，但还是想来这个地方露个脸，哈哈）
http://www.zealer.com

**Comment by Geew** [comment]
# var letvcloud_player_conf =  {"uu":"9a41a0d696","vu":"141d24b931","auto_play":0,"gpcflag":1,"width":1000,"height":563,"extend":0}
页面上可以拿到vu的, 然后api在you-get里面可以找到, 我只能帮你到这里了喵

**Comment by zythum** [comment]
https://github.com/zythum/mama2/issues/104
