### ISSUE TITLE
使用服务器缓存降低流量消耗

### ISSUE THREAD

**Issue by fanthos** [zythum/mama2#169]
服务器上的index.js大概有12k，相当于用户每次访问视频时服务器都要消耗12k的流量。
用服务器缓存应该能把每次访问视频的流量消耗降低到1k以下，可以降低服务器费用。

**Comment by gdshen95** [comment]
在服务器上做缓存，客户端这边不还是要请求12k的index.js么？怎么降低服务器的流量？

**Comment by cuilili** [comment]
http 304,   如果文件没有发生变化, 就不会再传输数据了

**Comment by gdshen95** [comment]
我理解错了，谢谢

**Comment by cuilili** [comment]
如果缓存的话,用户第一次会请求完整的文件, 之后再访问的话确实可以节省很多流量.
