### ISSUE TITLE
优酷只能看标清吗？

### ISSUE THREAD

**Issue by nickkwok** [zythum/mama2#17]
优酷只能看标清吗？记得以前能看高清的。

**Comment by hedongjie** [comment]
貌似，刚刚也发现了只能看标清，正想问

**Comment by tlhc** [comment]
mark+1

**Comment by Under7degrees** [comment]
只能看标清

**Comment by enerai** [comment]
反馈，我这里 Chrome 也是只能看标清

**Comment by zythum** [comment]
目前chrome确实只有标清。因为mp4高清的现在抓的是分片的。所以暂时没有去支持

**Comment by zythum** [comment]
看这里 https://github.com/zythum/mama2/issues/82

**Comment by SingleOne** [comment]
我是OS X下用Safari看的，没用chrome
