### ISSUE TITLE
youku 挂掉了

### ISSUE THREAD

**Issue by rmbzlib** [zythum/mama2#170]
youku以挂，能否传授下怎么解析，这样就可以直接给你提pr了

**Comment by erguotou520** [comment]
感觉像是优酷重构了一次，代码整体结构都变了，以前的解析依赖于`window.videoId`，但现在没有这个变量了，`match`方法返回了`false`，刚缕了一遍之后得出的结果。可能得重新查找解析方法。

**Comment by erguotou520** [comment]
简单扫了眼优酷的代码，似乎视频相关的参数都放到了`PageConfig`对象下。

**Comment by zythum** [comment]
抱歉。前几天折腾别的事情了。已经修复了
