### ISSUE TITLE
讨论优酷支持清晰度选择的问题

### ISSUE THREAD

**Issue by wenson** [zythum/mama2#18]
经过分析，可以在seeker_youku.js的235行添加
['高清', t._videoSegsDic['flv'][0].src],
['超清', t._videoSegsDic['mp4'][0].src],
可以选择清晰度，但只能播放第一段的视频。
猜测如果需要全部都能播放，需要播放器支持播放列表。
![hd2](https://cloud.githubusercontent.com/assets/1856557/6919632/5bbd9e94-d7eb-11e4-9530-071c0f7a38f2.png)

**Comment by yayanong** [comment]
就是说看30分钟内的动画片,应该可以用这个方法的,对吧?

**Comment by wenson** [comment]
他的视频是分段的，只要视频只有一段的话就可以使用这个方法。如果有多段，还没想到方法弄。

**Comment by zythum** [comment]
https://github.com/zythum/mama2/issues/83
