### ISSUE TITLE
chrome下没暂时还没有插件吗?

### ISSUE THREAD

**Issue by yayanong** [zythum/mama2#19]
safari下插件可用,chrome图标看到是灰色,是还没开发吗?

**Comment by enerai** [comment]
希望看到插件哈~

**Comment by Jamesits** [comment]
https://chrome.google.com/webstore/detail/%E5%A6%88%E5%A6%88%E5%86%8D%E4%B9%9F%E4%B8%8D%E7%94%A8%E6%8B%85%E5%BF%83%E6%88%91%E7%9A%84-macbook-%E5%8F%91%E7%83%AD%E4%BA%86%E8%AE%A1%E5%88%92/gijmbahogfcideengmpajidjealpfjjf

@yayanong @enerai 先放一个临时能用的……

**Comment by zythum** [comment]
chrome 用妈妈计划的体验并不好，所以没有放出。插件是写了。你可以从github下到。
