### ISSUE TITLE
bilibili的清晰度不高希望能改善下

### ISSUE THREAD

**Issue by min09577** [zythum/mama2#23]
bilibili的清晰度不高希望能改善下

**Comment by zhaidoudou123** [comment]
是啊 b站1080p全都载入不了

**Comment by Dereshi** [comment]
Mac的话，可以试试https://github.com/typcn/bilibili-mac-client

**Comment by zythum** [comment]
目前bilibili给出的mp4源就是这样的。我也没有其他办法
