### ISSUE TITLE
Yosemite 10.10.3的Safari中将画面放大至全屏时非常卡顿

### ISSUE THREAD

**Issue by yc2prime** [zythum/mama2#24]
不知道是不是我的个例。

**Comment by cwbsw** [comment]
你可以试试单击右键选择进入全屏幕。

**Comment by zythum** [comment]
确实会。但是我调用的是系统api.... 右键只有播放器会全屏。会少很多的dom渲染。估计会不卡一下。但是右键的话bilibili就看不到弹幕了哦，
