### ISSUE TITLE
about firefox

### ISSUE THREAD

**Issue by rtsun** [zythum/mama2#26]
it seems not compatible with my firefox.it shows loading all the time.did u got plan on this? thx anyway.

**Comment by zythum** [comment]
mama2 just work on chrome and safari. sorry about firefox. :(

2015-05-12 19:42 GMT+08:00 rtsun <notifications@github.com>:

> it seems not compatible with my firefox.it shows loading all the time.did
> u got plan on this? thx anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zythum/mama2/issues/26>.
>



-- 
朱一
