### ISSUE TITLE
其实我就是好奇两个问题和附带一个建议。。

### ISSUE THREAD

**Issue by lifangzheng** [zythum/mama2#27]
1. 通过这个脚本加载的应该是mp4视频吧，为什么cpu虽然比flash少了很多但还是比本地看视频高呢？
2. 为何没装flash也能看到b站的弹幕，这是什么黑科技。。

希望能做成safari和chrome插件。。每次看一个视频都要点一次书签好麻烦的。。

**Comment by lifangzheng** [comment]
and 优酷和土豆在新加坡看不了，只能加载出时间和初始界面。b站和爱奇艺正常。优酷土豆flash模式正常。

**Comment by zythum** [comment]
1. 这个我努力
2. 因为弹幕是我取的数据我自己渲染的。所以可以
3. safari有插件。chrome因为源清晰度的原因暂时不发插件。
4. 这个暂时不知道。我没有去过新加坡...
