### ISSUE TITLE
请支持优酷选择粤语

### ISSUE THREAD

**Issue by 13kay** [zythum/mama2#3]
请支持优酷选择粤语。谢谢。

**Comment by zythum** [comment]
目前还没有找到解决方法。求大（nei）神（bu）姥（yuang）爷（gong）支持

**Comment by shiniv** [comment]
我找到了一个比较笨的方法
先抓取http://v.youku.com/player/getPlayList/VideoIDS/XMzM5MzgxMTUy/ctype/12/ev/1里面的内容
如果有粤语的话 会在dvd段看到这个
![image](https://cloud.githubusercontent.com/assets/3983330/6860753/62165a10-d467-11e4-80fa-c0fd0ba0ef44.png)
然后继续解析粤语的链接 :)

**Comment by zythum** [comment]
我试试...
