### ISSUE TITLE
全屏的时候controller不能隐藏啊

### ISSUE THREAD

**Issue by chm512512** [zythum/mama2#30]
全屏的时候controller不能隐藏啊，一直上下动。。。

**Comment by zythum** [comment]
浏览器是safari么？

**Comment by chm512512** [comment]
360急速。顺便补一句~搜狐好像用不了。提示当前版本不提供服务

**Comment by zythum** [comment]
我周末去看下。前端时间一直没时间看视频5555555555

我没有360有mac版本么？

**Comment by chm512512** [comment]
额。。。小白坐等大神修复~有时间看视频的路过~
360急速貌似没有mac版本额。。。
————————————————————————
360极速浏览器	7.5.3.318 (Branch of Chromium 30.0.1599.101 ) 
操作系统	Windows 
Blink	537.36
JavaScript	V8 3.20.17.15
Flash	11,6,602,180
用户代理	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36 QIHU 360EE
—————————————————————————
额，这些能不能提供帮助?
