### ISSUE TITLE
播放优酷、土豆视频BUG

### ISSUE THREAD

**Issue by zilongchina** [zythum/mama2#33]
表现：使用MAMA2方式观看优酷和土豆的长视频时，只能显示前40min的视频。后续部分无法继续加载。（如：此[优酷](http://t.cn/R28URno)和[土豆](http://t.cn/R2TT4lL)视频实际长度为78:04，MAMA2只能播放前40min）
经测试，此现象在哔哩哔哩、爱奇艺、搜狐不存在。

**Comment by wenson** [comment]
那是mama2 不支持 分段播放造成的。无力研究这个 ：（

**Comment by zythum** [comment]
https://github.com/zythum/mama2/issues/83
