### ISSUE TITLE
支持Acfun

### ISSUE THREAD

**Issue by cnbeining** [zythum/mama2#4]
这个有点麻烦。

JS苦手，这里丢下思路：

1.0 读页面以获得vid

或者：

1.1 解析页面地址
1.2 使用API从aid换vid

2. 写如下解析器：

- 乐视云
- 优酷
- Sina
- 土豆

（虽然还有别的，但是罕见

3. 放！

这个注定必须自己实现，鉴于猴子因为解析已经进去捡肥皂过了，飞驴的开发者和管理员已经失联一个星期多了。。。

我就说说，我不写，我不会写，恩。

**Comment by zythum** [comment]
好的。之前ac的解析器写过。基本实现是这样子的。但是非常不稳定。就没有放出来。我回去加上看看

**Comment by zythum** [comment]
https://github.com/zythum/mama2/issues/104
