### ISSUE TITLE
搜狐视频报错

### ISSUE THREAD

**Issue by qshenx** [zythum/mama2#41]
当前版本不再提供播放服务，请升级到最新版客户端

**Comment by zythum** [comment]
把浏览地址给朱一吧...

**Comment by langrenfengzi** [comment]
似乎不再支持mp4格式的播放了，任意找个mp4地址都是如此。
http://api.tv.sohu.com/v4/video/info/2437906.json?site=1&api_key=695fe827ffeb7d74260a813025970bd5&sver=1&partner=1&callback=MAMA2_HTTP_JSONP_CALLBACK0

**Comment by zythum** [comment]
是给mp4不提供服务了么。其实朱一一致测试用safari。木有发现。但是我看h5页面已经只能看5分钟了。要5分钟的没有意义啊。我看看还能不能找回来...

**Comment by zythum** [comment]
上周一忙吧这个忘掉了。明天我折腾下... mark
