### ISSUE TITLE
无限黑屏。。。

### ISSUE THREAD

**Issue by byljcron** [zythum/mama2#5]
确定只要书签就行了吗。。。
系统archlinux64位
火狐36.0.4
打开视屏后视屏地址获取后会跳出一个无限黑屏的窗口。。。里面毛线都没有。。。

**Comment by yfdyh000** [comment]
+1。Win8.1+Firefox 37+小书签，B站或优酷都是无限黑屏。

**Comment by zythum** [comment]
抱歉暂不支持火狐...

**Comment by wenketel** [comment]
请求支持
