### ISSUE TITLE
在优酷上看视频的时候选择超清但是播放的是标清的视频

### ISSUE THREAD

**Issue by SingleOne** [zythum/mama2#64]
在优酷上看视频的时候选择超清但是播放的是标清的视频，是不是地址解析的问题？

**Comment by biochemputer** [comment]
同意，我也遇到这个问题了

**Comment by karin13** [comment]
你是用哪个浏览器播放的？优酷的HTML5超清视频只支持safari

**Comment by biochemputer** [comment]
OK. 我用的是chrome

**Comment by XhstormR** [comment]
chrome一直都不能选清晰度，貌似不是BUG

**Comment by zythum** [comment]
看这里 https://github.com/zythum/mama2/issues/82
