### ISSUE TITLE
腾讯视频已对 Mac 用户默认开启了 HTML5 Video 模式视频播放，欢迎大家使用与吐槽

### ISSUE THREAD

**Issue by rpsh** [zythum/mama2#66]
HTML5 Video 亦有提供各种清晰度切换。 http://v.qq.com/ 

![default](https://cloud.githubusercontent.com/assets/817125/10077467/fe975d96-6312-11e5-9b0c-c0688d5497d9.png)

*怀念 Flash 模式播放的可以点 「省电模式」开关，关掉省电模式，切换回 Flash 「风扇模式」

**Comment by zythum** [comment]
鹅长视频 good job.   话说Flash真的省电么？

**Comment by wenson** [comment]
Good job

**Comment by 18768108070** [comment]
真是个好消息

**Comment by rpsh** [comment]
@zythum  HTML5 Video 模式为「省电模式」，点一下关掉省电模式，就变成 Flash （不省电）

**Comment by rpsh** [comment]
@zythum 方便的话可以在 **妈妈再也不用担心我的macbook发热了计划2**  上标注一下腾讯视频已原生支持 Video 播放吗？

感谢 🙏

**Comment by A-Circle-Zhang** [comment]
话说你是腾讯视频的员工么...
mama2 中的腾讯视频的部分是我完成的，你们这样就让我们又多了一种得到一个不限速的视频 v k e y 的方法，还没一点难度...
这样真的好吗？...

**Comment by zythum** [comment]
@rpsh 已经在homepage和readme的显眼的位置加上了。

@A-Circle-Zhang 一环菌。你这么说真的好么。你非要来点难度是么..2333333

**Comment by A-Circle-Zhang** [comment]
@rpsh 我错了，看起来是有阶梯限速的

**Comment by rpsh** [comment]
@A-Circle-Zhang  😇😇😇

**Comment by Demodi** [comment]
@rpsh 刚刚在真探等美剧下面，还是 flash 播放。没有省电模式

**Comment by rpsh** [comment]
@Demodi  抱歉，由于相关方要求，我们需要在最近一段时间回退到 Flash 模式，会在十月中旬切回默认 HTML5 Video 模式。 （当前，如果禁用 Flash 插件可以继续走 HTML5 video）

**Comment by Demodi** [comment]
@rpsh 谢谢

**Comment by markhuang1212** [comment]
赞一个
