### ISSUE TITLE
优酷同时两个视频在播放

### ISSUE THREAD

**Issue by dragonly** [zythum/mama2#71]
使用mama2放优酷的时候，页面上原本的flash也一直没有关掉，chrome和safari都一样，Chrome Version 46.0.2490.71 (64-bit)，Safari Version 9.0.1 (11601.2.7.2)

**Comment by zythum** [comment]
我这可以。是浏览器的原因么？  我的原理是吧这个页面上的flash都干掉了。
逻辑在: 
https://github.com/zythum/mama2/blob/master/src/flashBlocker.js

**Comment by dragonly** [comment]
ok,有空我track一下看看，因为我的mbp上有问题，不知道具体是哪里的代码没有执行还是怎样

**Comment by wtser** [comment]
我也曾遇到过，怀疑是页面没载入完就使用 mama2了导致
