### ISSUE TITLE
Safari & Chrome，土豆网

### ISSUE THREAD

**Issue by Daymond** [zythum/mama2#72]
1、Safari浏览器的插件&Bookmarklet无法正确解析土豆网视频长度（44min的视频解析之后只有40min）；
2、Chrome浏览器的Bookmarklet无法选择视频清晰度；
3、Chrome浏览器的Bookmarklet无法全屏观看。

麻烦开发者了！

**Comment by zythum** [comment]
https://github.com/zythum/mama2/issues/83
