### ISSUE TITLE
请在浏览器插件下载区域说明一下插件封装的时间 :-)

### ISSUE THREAD

**Issue by Yuki-Judai** [zythum/mama2#8]
Hi，大神辛苦了，新的妈妈计划用起来很好，新的播放器界面也好好看。希望能在浏览器插件下载区域说明一下插件封装的时间，这样我们就能知道自己下载的插件是不是该更新了。:-) 大神辛苦了。

**Comment by zythum** [comment]
浏览器插件的作用和bookmarklet是一样的。所以不需要更新。主要朱一上线版本。你就一直会是最新版本。
