### ISSUE TITLE
seeker_youku.js 迷之代码

### ISSUE THREAD

**Issue by dragonly** [zythum/mama2#84]
想看看能不能帮忙做点chrome的贡献,发现里面的代码好像是uglify过的...不知道是什么意思,觉得只让大家方便来增加seeker,而你自己全权拥有repo的维护权吗 0 0...
没有恶意,只是觉得怪怪的,大部分代码都是可以看的,只有这么一些蜜汁代码

**Comment by zythum** [comment]
seeker_youku 里面的算法代码是我分析youku的js源码摘出来的算法代码。说白了朱一自己都不知道具体什么意思。所以我也没法给她搞成你能看懂的。
mama2本身就是开源的。你自己都可以fork一份自己搞自己的。我只是维护我自己repo，并且有个很多人用的线上版本。你可以不提交给我自己用，也可以分享给大家一起用。
我自己当然要保证大家给我提交的seeker是可用的。并且不会把其他东西搞坏，不会做一些不该做的事情。（上传用户隐私什么的其实是很容易的事情。在这种浏览器插件或者bookmark脚本上面。）

你看着是蜜汁代码。但是你想想朱一是要在5000多行蜜汁代码里面摘出解析必须的蜜汁代码是不是也是很辛苦的工作...233333

**Comment by dragonly** [comment]
原来如此 0 0

track过微博的登录逻辑，还是有类似经历的，辛苦辛苦。。
我只是觉得pr能让大家直接一起用（如果能用的话>.<
