### ISSUE TITLE
朱大大你好，请问youku根据视频id计算那三个值的步骤是怎么得到的？想了解一下。

### ISSUE THREAD

**Issue by newbaidu** [zythum/mama2#88]
朱大能具体告知在哪个js里吗，以后优酷改算法，也想研究研究。
谢谢了。

**Comment by zythum** [comment]
－ －。 这个真只是硬摘优酷的js代码然后看里面。里面有关于id加密计算逻辑。因为代码有混淆，所以不是特别好弄
