### ISSUE TITLE
How about airplay support?

### ISSUE THREAD

**Issue by Willian-Zhang** [zythum/mama2#93]
- [ ] #94

**Comment by Willian-Zhang** [comment]
剛看到這裡： https://github.com/zythum/mamaplayer/pull/2

辛苦啦，新年快樂

**Comment by zythum** [comment]
好的 这几天去乡下了 回去验证下 感谢

发自我的 iPhone

**Comment by zythum** [comment]
已经在mamaplayer  中merge。 感谢
