### ISSUE TITLE
Load Script From Local?

### ISSUE THREAD

**Issue by Willian-Zhang** [zythum/mama2#95]
https://github.com/zythum/mama2/commit/28a6bf4326055e4fdf7cf214bd25c4692ec7966e

remote loading sometimes downs，
Safari plugin do support upgrading right？

**Comment by zythum** [comment]
我还是觉得拉线上代码好一些 本身代码量不大就一个文件。如果用户没有开启自动更新和及时更新就可能失效了. 

发自我的 iPhone

**Comment by Willian-Zhang** [comment]
增加一個選項呢2333
