### ISSUE TITLE
好像代码里不全啊?没看到解析乐视TV的代码

### ISSUE THREAD

**Issue by taizilongxu** [zythum/mama2#96]
RT, 是要 @A-Circle-Zhang  童鞋吗?

**Comment by A-Circle-Zhang** [comment]
主要还是给普通用户使用的。
如果你出于个人学习目的或者商业用途需要解析源代码，可以先到 GitHub 上其它项目去看看，比如 https://github.com/soimort/you-get 。

**Comment by taizilongxu** [comment]
主要想看看代码, 多谢: )
